export const layout = {
  screenPaddingX: 20,
  screenPaddingBottom: 20,
  tabScreenPaddingTop: 65,
  headerIconSize: 30,
  headerTitleSize: 20,
  headerMarginBottom: 30,
  sectionLabelTop: 18,
  sectionLabelBottom: 12,
  smallTextSize: 12,
  bodyTextSize: 16,
  chipWidth: 132,
  chipRadius: 12,
  cardRadius: 12,
  notesRadius: 12,
  primaryButtonRadius: 16,
  pageGap: 28,
} as const;